import type { AppModule, AppModuleId } from "../types";

export const appModules: AppModule[] = [
  {
    id: "home",
    title: "Home",
    shortTitle: "Home",
    description: "Daily brief, system status, and launch surface.",
    group: "home",
    status: "active",
  },
  {
    id: "notes",
    title: "Notes",
    shortTitle: "Notes",
    description: "Read, write, and organize the Obsidian vault.",
    group: "knowledge",
    status: "active",
  },
  {
    id: "tasks",
    title: "Tasks",
    shortTitle: "Tasks",
    description: "Markdown-backed actions connected to notes.",
    group: "home",
    status: "active",
  },
  {
    id: "terminal",
    title: "Terminal",
    shortTitle: "Terminal",
    description: "Web terminal into the brain tmux session.",
    group: "knowledge",
    status: "active",
  },
  {
    id: "system",
    title: "System",
    shortTitle: "System",
    description: "Service state, sync, and infrastructure register.",
    group: "knowledge",
    status: "active",
  },
  {
    id: "health",
    title: "Health Overview",
    shortTitle: "Overview",
    description: "Fast health capture, today's state, and recent corrections.",
    group: "health",
    status: "active",
  },
  {
    id: "health-log",
    title: "Health Log",
    shortTitle: "Log",
    description: "Daily logging chat, timeline, and backfill.",
    group: "health",
    status: "active",
  },
  {
    id: "health-food",
    title: "Food",
    shortTitle: "Food",
    description: "Meal patterns and loose food logs.",
    group: "health",
    status: "planned",
  },
  {
    id: "fitness",
    title: "Fitness",
    shortTitle: "Fitness",
    description: "Workout calendar, sets, and recurring sessions.",
    group: "health",
    status: "active",
  },
  {
    id: "health-body",
    title: "Body",
    shortTitle: "Body",
    description: "Sleep, recovery, energy, soreness, and body notes.",
    group: "health",
    status: "planned",
  },
  {
    id: "money",
    title: "Money Overview",
    shortTitle: "Overview",
    description: "Spending, budgets, and what's coming up.",
    group: "money",
    status: "planned",
  },
  {
    id: "shopping",
    title: "Shopping",
    shortTitle: "Shopping",
    description: "Needs hierarchy: essential, important, nice-to-have.",
    group: "money",
    status: "active",
  },
  {
    id: "budget",
    title: "Budget",
    shortTitle: "Budget",
    description: "Monthly limits and category targets.",
    group: "money",
    status: "planned",
  },
  {
    id: "expenses",
    title: "Expenses",
    shortTitle: "Expenses",
    description: "Recent transactions and recurring bills.",
    group: "money",
    status: "planned",
  },
];

export function getAppModule(id: AppModuleId) {
  return appModules.find((module) => module.id === id) ?? appModules[0];
}
