FROM node:22-alpine AS build

WORKDIR /app
COPY apps/console/package*.json ./
RUN npm ci

COPY apps/console ./
RUN npm run build

FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=80
ENV PUBLIC_ROOT=/app/public
ENV VAULT_ROOT=/vault

COPY --from=build /app/dist /app/public
COPY --from=build /app/dist-server /app/dist-server

EXPOSE 80
CMD ["node", "dist-server/server.js"]
